### ISSUE TITLE
Great Submission but you need to store the most recent operation

### ISSUE THREAD

**Issue by KapsonLabs** [Akinbola247/calculator-with-functionality#1]
Hey @Akinbola247. Your submission is great but refer to the document again and read the last sections about using a suitable data structure to store the most recent operation.

Remember only the most recent operation should show above the answer. E.g
If operation 1 = 1+3
   answer = 4

and next operation = 4+5
and answer = 9

The operation stored and displayed is the most recent operation which is 4+5

**Comment by Akinbola247** [comment]
Hello sir @KapsonLabs. I just made adjustment to my submission and I have updated the code according to your specification, kindly take a look at it to be sure I got the corrections right. Thank you for your time sir.
